apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../crd/rehearsal.io_rehearsalruns.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - networkpolicy.yaml
# Apply secret.example.yaml manually or create via kubectl create secret
